### ISSUE TITLE
Allow clearing the cached value

### ISSUE THREAD

**Issue by koliyo** [Alorel/typescript-lazy-get-decorator#84]
- [x] I have read the README and API docs (if applicable); the issue is not covered there.
- [x] I have searched the repository issues and pull requests; my query is not covered there.

-----

- **Describe the feature**: 

I would like to be able to reset the cached properties based on certain events. So when this event happens the property must be evaluated again.

- **Why it is needed** (include use cases): The caching is only valid until specific class object mutations happens
 
- **Pseudocode** (non-functional schematic of how it could operate):
Not sure, some global accessor on class level, or some handle/reverse-callback passed to LazyGetter?
- [ ] I would be able to implement this feature and make a pull request.
  
-----

Additional information goes here.

**Comment by Alorel** [comment]
This is a bit tricky to implement in a decorator. I'm proposing a syntax like this:

```typescript
const lazyGetForFoo = LazyGetter();
const lazyGetForBar = LazyGetter(true);

class MyClass {
  @lazyGetForFoo
  get foo() {
 	return 1;
  }

  @lazyGetForBar
  get bar() {
    return 2;
  }

  @LazyGetter()
  get qux() {
    // This one won't be clearable
    return 3;
  }

  clearFoo() {
    lazyGetForFoo.clear(this); // give it an instance reference
  }

  cleanBar() {
    lazyGetForBar.clear(this);
    // It would automatically detect if a value is set on the prototype, not just the instance
    // This would be less stable as it wouldn't clear instance-level caches on other active instances of MyClass
  }
}
```

What do you think?

**Comment by koliyo** [comment]
Yes that might work!

Or maybe something like, not sure if possible:
```js
@LazyGetter({id: 'foo'})
get foo() {
  return 1
}

clearFoo() {
  this._lazyGetters.foo.clear()
}

```

**Comment by Alorel** [comment]
I wouldn't be too keen on changing the method signature, though, as it
could result in a bit of a migration hell.

I'll try to patch something together in the coming days 👍
